name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-lastest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v4
      - name: Say Hello
        uses: echo "Hello World"
        